spring:
  profiles:
    active: dev
---
server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com #eureka服务端实例名称
  client:
    register-with-eureka: false #代表是否向注册中心注册自己
    fetch-registry: false #false代表自己是注册中心
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
spring:
  profiles: dev
  application:
    name: springcloud-server-dept
---
server:
  port: 7003
eureka:
  instance:
    hostname: eureka7003.com #eureka服务端实例名称
  client:
    register-with-eureka: false #代表是否向注册中心注册自己
    fetch-registry: false #false代表自己是注册中心
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
spring:
  profiles: test
  application:
    name: springcloud-server-dept